baseURL: "https://budibase.com/"
languageCode: "en-uk"
title: "Budibase | Build internal tools in minutes, the easy way"
theme: "budibase"
enableEmoji: "true"
disableKinds: ["taxonomy"]
ignoreErrors: ["error-disable-taxonomy"]
copyright: "This work is licensed and owned by Budibase"

markup:
  goldmark:
    rendered:  
      hardWraps: "true"
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

paginate: 8

params:
  keywords: ["Low code platform", "Custom software", "Web application builder", "internal tools", "internal tool builder"]
  description: "Budibase is a modern, open source low-code platform for building modern internal applications in minutes."
  dateform: "Jan 2, 2006"
  lang: "en"
  images: ['budibase-gradient.jpg']
  cloudinary_base_url: "https://res.cloudinary.com/daog6scxm/image/upload"

author:
  name: "Joseph Johnston"

params.publisher:
  name: "Budibase"

params.publisher.logo:
  url: "/budibase-logo.png"

params.logo:
  url: "/budibase-logo.png"




