baseURL: "https://budibase.com/"
languageCode: "en-uk"
title: "Budibase | Create business apps in mins | Open-source low-code platform"
theme: "budibase"
enableEmoji: "true"
disableKinds: ["taxonomy"]
ignoreErrors: ["error-disable-taxonomy"]
copyright: "This work is licensed and owned by Budibase"

markup:
  goldmark:
    rendered:  
      hardWraps: "true"

taxonomies:
  category: "categories"
  tag: "tags"
  integrationcategory: "integrationcategories"
  featured: "featured"

params:
  keywords: ["Low code platform", "Custom software", "Web application builder", "internal tools", "internal tool builder"]
  description: "Budibase is a modern, open source low-code platform for building modern internal applications in minutes."
  dateform: "Jan 2, 2006"
  lang: "en"
  images: ['budibase-ui-gradient.png']

author:
  name: "Joseph Johnston"

params.publisher:
  name: "Budibase"

params.publisher.logo:
  url: "/budibase-logo.png"

params.logo:
  url: "/budibase-logo.png"


