---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/legal
  label: Legal
  create: all
  match: "**/*"
- type: directory
  path: content/logistics
  label: Logistics
  create: all
  match: "**/*"
- type: directory
  path: content/admin-panels
  label: Admin panels
  create: all
  match: "**/*"
- type: directory
  path: content/approval-apps
  label: Approval apps
  create: all
  match: "**/*"
- type: directory
  path: content/portals
  label: Portals
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/templates
  label: Templates
  create: all
  match: "**/*"
- type: directory
  path: content/internal-tools
  label: Internal tools
  create: all
  match: "**/*"
- type: directory
  path: content/integration
  label: Integration
  create: all
  match: "**/*"
- type: directory
  path: content/forms
  label: Forms
  create: all
  match: "**/*"
- type: directory
  path: content/careers
  label: Careers
  create: all
  match: "**/*"
- type: directory
  path: content/business-apps
  label: Business apps
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: cms
public_path: https://res.cloudinary.com/daog6scxm/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
